import './globals.css'
import type { Metadata } from 'next'
import { Spectral } from 'next/font/google'
import Navbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'

const spectral = Spectral({ subsets: ['latin'], weight:['300'] })

export const metadata: Metadata = {
  title: 'AzrBoutiqe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spectral.className} suppressHydrationWarning={true}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
