"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Spectral } from 'next/font/google'
import Navbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'
import { ReactNode } from 'react'
import { SessionProvider } from 'next-auth/react'

const spectral = Spectral({ subsets: ['latin'], weight:['300'] })

export const metadata: Metadata = {
  title: 'AzrBoutiqe',
  description: 'Generated by create next app',
}

interface Layout{
  children:ReactNode,
  session:any
}

export default function RootLayout({
  children, session
}:Layout) {
  return (
    <html lang="en">
      <body className={spectral.className} suppressHydrationWarning={true}>
        <SessionProvider session={session}>
          <Navbar/>
          {children}
          <Footer/>
        </SessionProvider>
      </body>
    </html>
  )
}
